---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubesat-planckster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dream-aim-deliver/kubesat-planckster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubesat-planckster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: release
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: infrastructure
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubesat-planckster
  timeout: 2m0s
  wait: true
